# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "ES_06/01" ]
  pull_request:
    branches: [ "ES_06/01" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install all dependencies
      run: yarn --prefer-offline

    - name: Run the tests
      run: yarn nx run store-merchandise:test
      
    - name: Run the lint
      run: yarn nx run store-merchandise:lint
      
    - name: Build the app
      run: yarn nx run admin:build:production




